### ISSUE TITLE
Npm name

### ISSUE THREAD

**Issue by ivanjeremic** [thinkholic/react-jetpack#4]
Hello, I see you own the name react-jetpack on npm and it is not maintained anymore, I want to ask you if you would donate the package name to me for my project I would really appreciate it? Thanks

**Comment by thinkholic** [comment]
Hey, I was actually thinking do another structured release as soon as possible. I started this in planning to support another project I'm working on. Anyway, would love to know more about your project, and I'm up to give it to you if it is more suitable for your work than mine. :)

**Comment by thinkholic** [comment]
Re-working on the project, so closing this issue.
